# Generated by Django 5.2 on 2025-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='books/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pages', models.IntegerField()),
                ('published_date', models.DateField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
