# Generated by Django 5.2 on 2025-05-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
    ]
