# Generated by Django 5.2 on 2025-05-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('slug', 'published_date')},
        ),
    ]
