# Generated by Django 5.2 on 2025-05-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='death_date',
        ),
    ]
